spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: blog-service
          uri: lb://blog-service
          predicates:
            - Path=/**
server:
  port: 9000
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"

# ---
# spring:
#   main:
#     web-application-type: none